stages:
    - build

build-image:
    image: docker:dind
    stage: build
    variables:
        IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    before_script:
        - dockerd > /var/log/dockerd.log 2>&1 &
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker build -t $IMAGE_TAG -t $CI_REGISTRY_IMAGE:latest .
        - docker push $IMAGE_TAG
        - docker push $CI_REGISTRY_IMAGE:latest
    only:
        - main
    tags:
        - felucia
