version: "3"

services:
  redis:
    image: redis:latest
    restart: always

  db:
    image: mongo:latest
    restart: always
    volumes:
      - screeps_mongo:/data/db

  screeps:
    image: registry.demannu.com/demannu/screeps_docker:master
    depends_on:
      - db
      - redis
    restart: always
    ports:
      - "21025:21025"
    environment:
      STEAM_API_KEY: <steamkey>

    volumes:
      - screeps_logs:/world/logs
      - screeps_assets:/world/assets

volumes:
  screeps_mongo:
  screeps_logs:
  screeps_assets:
